import type { Metadata } from "next";
import "./globals.css";
import { robotoMono } from "@/lib/fonts";
import { Toaster } from "@/components/ui/sonner"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  


  return (
    <html lang="en">
      <body
        className={`${robotoMono.className} antialiased w-full h-screen bg-white`}
      >
          {children}
          <Toaster />
      </body>
    </html>
  );
}
